# Generated by Django 2.0.5 on 2018-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_messages', '0002_auto_20180527_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemsg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='modulemsg',
            name='module_id',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='modulemsg',
            name='serial_no',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='stringmsg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
